version: "2"
services:
  es:
    image: elasticsearch:6.4.3
    container_name: master1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
     # - ./config/masterlogs/:/usr/share/elasticsearch/logs
     # - ./config/master1data:/usr/share/elasticsearch/data
      - ./config/esmaster.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
    user: "root"
    networks:
      - net-es
networks:
  net-es:
