# 构建本地存储
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
# 构建阿里云存储，此处提供配置样例，实际配置需要联系阿里云云存储供应商
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk
provisioner: disk.alibabacloud.com
parameters:
  type: cloud_ssd
  zoneId: <zone-id>
  fsType: ext4
reclaimPolicy: Delete