version: "2"
services:
  master:
    image: elasticsearch:6.4.3
    container_name: node_178_1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8250:8250"
      - "8260:8260"
    volumes:
      - ./config/esmaster.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
    networks:
     - net-es
networks:
  net-es:
