kind: Deployment
apiVersion: apps/v1
metadata:
  name: front
  namespace: uat
  labels:
    app: front
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-ng
          configMap:
            name: upstream-nginx-conf
            defaultMode: 420
      containers:
        - name: container-front
          image: ${IMAGE}
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 100Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-1rhinq
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: docker-repo
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600