version: "2"
services:
  logstash_client:
    image: logstash:6.7.0
    container_name: logstash_client
    restart: unless-stopped
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config:/usr/share/logstash/config
      - ./logs:/usr/share/logstash/logs
    command: "nohup logstash -f /usr/share/logstash/config/logstash.conf >>/usr/share/logstash/logs/nohup.out &"

